### ISSUE TITLE
The problem of decomposing the prompt into the sum of smaller prompts and low-rank products.

### ISSUE THREAD

**Issue by GarinLL** [ZhengxiangShi/DePT#11]
Hi, I see that the code for decomposing the prompt into the sum of smaller prompts and low-rank products in your paper is in **DePT/peft/tuners/prompt_tuning_lora.py**? If so, the code does not seem to reflect the decomposition of the prompt into the sum of smaller prompts and low-rank products, and it is still the code for prompt-tuning. Can you answer my doubts?

**Comment by ShiZhengyan** [comment]
We have `self.lora_embedding_A = nn.Parameter(torch.zeros((config.max_length, config.r)), requires_grad=True)` and `self.lora_embedding_B = nn.Parameter(torch.zeros((config.r, config.token_dim)), requires_grad=True)`.  Please check how they are used in the [code](https://github.com/ZhengxiangShi/DePT/blob/main/peft/peft_model.py#L834).

**Comment by GarinLL** [comment]
OK, I've seen that. Thanks a lot for your answer!
