### ISSUE TITLE
Could you please provide the checkpoints of MRQA datasets?

### ISSUE THREAD

**Issue by HungerPWAY** [ZhengxiangShi/DePT#9]

**Comment by ShiZhengyan** [comment]
Hi, I have included the available checkpoints, although not all of them are saved.

**Comment by HungerPWAY** [comment]
Thank for your reply. I am having some difficulties reproducing the MRQA dataset. Does these experiments require prompt initialization from other datasets?

**Comment by ShiZhengyan** [comment]
No, there is no need to do any transfer learning for initialization. From my experience, just training longer typically helps.

**Comment by HungerPWAY** [comment]
![image](https://github.com/ZhengxiangShi/DePT/assets/129951703/f2585256-faeb-41e3-84d9-6bd3ce9bfaf5)
In this highlighted context, it is mentioned that prompt initialization is from other datasets. Could you please specify which experiments need this opereation?

**Comment by ShiZhengyan** [comment]
Thanks for your question. This is only for the few-shot learning experiments.

In general, transfer learning can improve the speed of the convergence and the model performance. However, it might take a while or require some tricks to select the best source tasks. Therefore, in our experiments, when there are enough training examples, we typically train the soft prompt from the random initialization. In these cases, we find that training longer typically leads to better performance.

**Comment by HungerPWAY** [comment]
Does training require longer for other datasets? Could you please provide the checkpoints of the other datasets?
